### ISSUE TITLE
Failed to install for Step 2: Unable to open WPS Office by browser

### ISSUE THREAD

**Issue by yihuajack** [ZimoLoveShuang/wps-wakatime#1]
System: Windows 10 20H2 19042.685
Browser: Microsoft Edge 87.0.664.66, Google Chrome 89.0.4350.7, Mozilla Firefox 84.0 (x64 zh-CN)
WPS Office version: 11.3.0.9236 (校园版)
Description:
After visiting http://wps.zimo.wiki/publish.html in browser and clicking the `Install` button, the browsers showed:
![image](https://user-images.githubusercontent.com/23608500/103062974-d568a180-45ea-11eb-89c1-6e3663e3c243.png)
![image](https://user-images.githubusercontent.com/23608500/103063004-f204d980-45ea-11eb-9ff5-87f3a15d107c.png)
Click "确定" but nothing happened. Check `%APPDATA%\kingsoft\wps` there is no `jsaddons` folder.

**Comment by zimo0o0omiz** [comment]
Maybe you should try again with another browser

**Comment by yihuajack** [comment]
> Maybe you should try again with another browser

Well I have tried the 3 most popular browsers as is informed before, I don't think changing browsers will work.
btw the status is "invalid":
![image](https://user-images.githubusercontent.com/23608500/103068257-b9b7c800-45f7-11eb-91af-1b3d4cad5405.png)

**Comment by zimo0o0omiz** [comment]
It's just a display error. Refresh the page and it's OK

**Comment by yihuajack** [comment]
I believe it is not compatible with campus version. I switch to WPS Office PC version 11.1.0.10228 and it works.
![image](https://user-images.githubusercontent.com/23608500/103076711-533ba580-4609-11eb-8e9c-6fcd8b3257b5.png)

**Comment by zimo0o0omiz** [comment]
yes, that's right, just now I received this reply 
![image](https://user-images.githubusercontent.com/32027313/103076955-cf35ed80-4609-11eb-9713-9f64fe886763.png)
