### ISSUE TITLE
Invalid installation URL

### ISSUE THREAD

**Issue by hdadhich01** [ZimoLoveShuang/wps-wakatime#7]
http://wps.zimo.wiki/publish.html returns a server error

**Comment by tjuDavidWang** [comment]
I have the same problem.

**Comment by zimo0o0omiz** [comment]
已经停止支持此项目了

**Comment by alanhamlett** [comment]
If anyone wants to update this plugin, we can help host the install page at `wakatime.com`. Until then, I'm removing this plugin from the Supported IDEs page.
